INSERT INTO recette (idUser, nomRecette, descriptions, images, duree) VALUES 
(1, 'Gâteau au chocolat', 'Un délicieux gâteau au chocolat moelleux', 'chocolate_cake.jpg', 60),
(2, 'Salade César', 'Une salade César classique avec du poulet grillé', 'caesar_salad.jpg', 20),
(3, 'Soupe de légumes', 'Une soupe saine et réconfortante avec des légumes frais', 'vegetable_soup.jpg', 45),
(1, 'Pizza Margherita', 'Une pizza classique avec de la tomate, de la mozzarella et du basilic', 'pizza_margherita.jpg', 30),
(2, 'Pâtes Carbonara', 'Des pâtes italiennes crémeuses avec du bacon et du parmesan', 'pasta_carbonara.jpg', 25),
(3, 'Ratatouille', 'Un plat français de légumes mijotés', 'ratatouille.jpg', 50),
(1, 'Poulet Curry', 'Un curry de poulet épicé', 'chicken_curry.jpg', 40),
(2, 'Burger Maison', 'Un burger maison avec du boeuf, du fromage et des légumes frais', 'home_burger.jpg', 35),
(3, 'Tarte aux pommes', 'Une tarte traditionnelle aux pommes', 'apple_pie.jpg', 70),
(1, 'Lasagnes', 'Des lasagnes avec de la viande hachée, des tomates et du fromage', 'lasagna.jpg', 90),
(2, 'Quiche Lorraine', 'Une quiche avec des lardons et du fromage', 'quiche_lorraine.jpg', 45),
(3, 'Moules marinières', 'Des moules cuisinées avec du vin blanc et des échalotes', 'moules_mariniere.jpg', 30),
(1, 'Sushis', 'Des sushis variés avec du poisson frais', 'sushi.jpg', 60),
(2, 'Pancakes', 'Des pancakes moelleux avec du sirop d''érable', 'pancakes.jpg', 20),
(3, 'Paella', 'Un plat espagnol de riz avec des fruits de mer et du safran', 'paella.jpg', 75);



INSERT INTO etapes (nomEtape, duree, idRecette) VALUES 
('Mélanger les ingrédients secs', 10, 1),
('Ajouter les œufs et le chocolat fondu', 15, 1),
('Cuire au four', 35, 1),
('Préparer la laitue et les légumes', 10, 2),
('Griller le poulet', 10, 2),
('Mélanger tous les ingrédients', 5, 2),
('Couper les légumes', 10, 3),
('Faire cuire les légumes', 30, 3),
('Mixer la soupe', 5, 3),
('Préparer la pâte à pizza', 15, 4),
('Ajouter les garnitures', 5, 4),
('Cuire la pizza', 10, 4),
('Cuire les pâtes', 10, 5),
('Préparer la sauce carbonara', 15, 5),
('Mélanger les pâtes et la sauce', 5, 5),
('Couper les légumes', 15, 6),
('Faire mijoter les légumes', 35, 6),
('Cuire le poulet', 20, 7),
('Préparer la sauce curry', 10, 7),
('Mélanger le poulet et la sauce', 10, 7),
('Préparer le boeuf haché', 10, 8),
('Assembler les burgers', 10, 8),
('Cuire les burgers', 15, 8),
('Préparer la pâte', 20, 9),
('Couper les pommes', 10, 9),
('Cuire la tarte', 40, 9),
('Préparer les lasagnes', 30, 10),
('Cuire les lasagnes', 60, 10),
('Préparer la pâte à quiche', 15, 11),
('Ajouter les garnitures', 10, 11),
('Cuire la quiche', 20, 11),
('Nettoyer les moules', 10, 12),
('Cuire les moules', 20, 12),
('Préparer le riz', 20, 13),
('Rouler les sushis', 40, 13),
('Préparer la pâte à pancakes', 10, 14),
('Cuire les pancakes', 10, 14),
('Préparer les ingrédients', 20, 15),
('Cuire la paella', 55, 15);


INSERT INTO enregistrement (idUser, idRecette) VALUES 
(1, 1),
(2, 2),
(3, 3),
(1, 4),
(2, 5),
(3, 6),
(1, 7),
(2, 8),
(3, 9),
(1, 10),
(2, 11),
(3, 12),
(1, 13),
(2, 14),
(3, 15);



